/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_Control;

import Servicios.CarritoDeCompras;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Servicios.ConexionBD;
import Servicios.Product;
import static Vista_Control.ConsultasConso.products;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class ConsultasVideo extends javax.swing.JFrame {

    static ArrayList<Product> products = new ArrayList<>();

    /**
     * Creates new form Consultas
     */
    public ConsultasVideo() {
        this.setLocationRelativeTo(null);
        conexion = new ConexionBD();
        conexion.usarBD("proyecto_final");
        conexion.conectar();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVideojuegos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(471, 540));
        setPreferredSize(new java.awt.Dimension(471, 540));
        setResizable(false);
        setSize(new java.awt.Dimension(471, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVideojuegos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblVideojuegos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 390, 330));

        jLabel2.setFont(new java.awt.Font("Zilla Slab", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Consulta Videojuegos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Zilla Slab", 1, 18)); // NOI18N
        jButton2.setText("CONSULTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 150, 40));

        jButton3.setFont(new java.awt.Font("Zilla Slab", 1, 18)); // NOI18N
        jButton3.setText("Añadir al carrito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
                jButton3OnPressAddToShoppingCart(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 180, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\meaf7\\Downloads\\WhatsApp Image 2021-06-09 at 7.37.43 PM.jpeg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -680, 900, 1620));

        jButton1.setFont(new java.awt.Font("Zilla Slab", 1, 18)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 150, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Se ha terminado con la ejecución", "Conexion Terminada", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        jButton2.setVisible(false);
        
        ResultSet resultado = null;

        DefaultTableModel tabla = new DefaultTableModel();
        tblVideojuegos.setModel(tabla);

        tabla.addColumn("Almacen");
        tabla.addColumn("Nombre");
        tabla.addColumn("Referencia");
        tabla.addColumn("Tipo");
        tabla.addColumn("Precio");

        resultado = conexion.consultarBD("select * from videojuegos;");

        String fila[] = new String[5];
        try {
            while (resultado.next()) {

                Product product = new Product(resultado,true);
                products.add(product);

                fila[0] = product.Almacen;
                fila[1] = product.Nombre;
                fila[2] = product.Referencia;
                fila[3] = product.Tipo;
                fila[4] = product.Precio + "";

                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Gamestore.class.getName()).log(Level.SEVERE, null, ex);
        }

        conexion.cerrar();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3OnPressAddToShoppingCart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3OnPressAddToShoppingCart
        // TODO add your handling code here:
        int productIdx = tblVideojuegos.getSelectedRow();

        if (productIdx == -1) {
            JOptionPane.showMessageDialog(this, "You must select one product", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Product product = products.get(productIdx);
        CarritoDeCompras.AddProduct(product);
        Factura.DrawTable();

        JOptionPane.showMessageDialog(this, "Producto añadido");
    }//GEN-LAST:event_jButton3OnPressAddToShoppingCart

    ConexionBD conexion = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVideojuegos;
    // End of variables declaration//GEN-END:variables
}
