/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_Control;

import Servicios.CarritoDeCompras;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Servicios.ConexionBD;
import Servicios.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Laura Londoño
 */
public class ConsultasConso extends javax.swing.JFrame {

    static ArrayList<Product> products = new ArrayList<>();
    
    
    
    /**
     * Creates new form ConsultasConso
     */
    public ConsultasConso() {
        this.setLocationRelativeTo(null);
        conexion = new ConexionBD();
        conexion.usarBD("proyecto_final");
        conexion.conectar();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloL = new javax.swing.JLabel();
        TablaSP = new javax.swing.JScrollPane();
        ConsolasT = new javax.swing.JTable();
        ConsultarB = new javax.swing.JButton();
        AñadeB = new javax.swing.JButton();
        NombresL = new javax.swing.JLabel();
        VersionL = new javax.swing.JLabel();
        JavaVersionL = new javax.swing.JLabel();
        FondoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consolas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloL.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 48)); // NOI18N
        TituloL.setForeground(new java.awt.Color(255, 255, 255));
        TituloL.setText("Consultas Consolas");
        getContentPane().add(TituloL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 400, -1));

        ConsolasT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaSP.setViewportView(ConsolasT);

        getContentPane().add(TablaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 700, 350));

        ConsultarB.setBackground(new java.awt.Color(204, 204, 255));
        ConsultarB.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        ConsultarB.setForeground(new java.awt.Color(0, 0, 102));
        ConsultarB.setText("CONSULTAR");
        ConsultarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnPressConsultar(evt);
            }
        });
        getContentPane().add(ConsultarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 200, 60));

        AñadeB.setBackground(new java.awt.Color(204, 204, 255));
        AñadeB.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        AñadeB.setForeground(new java.awt.Color(0, 0, 102));
        AñadeB.setText("Añadir al carrito");
        AñadeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadeBActionPerformed(evt);
                OnPressAddToShoppingCart(evt);
            }
        });
        getContentPane().add(AñadeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 200, 60));

        NombresL.setForeground(new java.awt.Color(255, 255, 255));
        NombresL.setText("Andrés Charria / Catalina Alba / Sergio Pulido / Laura Londoño  ");
        getContentPane().add(NombresL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        VersionL.setForeground(new java.awt.Color(255, 255, 255));
        VersionL.setText("Product Version: Apache NetBeans IDE 12.2");
        VersionL.setToolTipText("");
        getContentPane().add(VersionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, -1));

        JavaVersionL.setForeground(new java.awt.Color(255, 255, 255));
        JavaVersionL.setText("Java: 1.8.0_111; Java HotSpot(TM) 64-Bit Server VM 25.111-b14");
        JavaVersionL.setToolTipText("");
        getContentPane().add(JavaVersionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        FondoL.setIcon(new javax.swing.ImageIcon("C:\\Users\\meaf7\\Downloads\\WhatsApp Image 2021-06-09 at 7.37.43 PM.jpeg")); // NOI18N
        getContentPane().add(FondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AñadeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadeBActionPerformed
        
    }//GEN-LAST:event_AñadeBActionPerformed

    private void OnPressConsultar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnPressConsultar
        ResultSet resultado = null;

        ConsultarB.setVisible(false);
        
        DefaultTableModel tabla = new DefaultTableModel();
        ConsolasT.setModel(tabla);

        tabla.addColumn("Almacen");
        tabla.addColumn("Nombre");
        tabla.addColumn("Referencia");
        tabla.addColumn("Color");
        tabla.addColumn("Dimensiones");
        tabla.addColumn("Precio");

        resultado = conexion.consultarBD("select * from consolas;");

        String fila[] = new String[6];
        try {
            while (resultado.next()) {

                Product product = new Product(resultado,false);
                products.add(product);
                
                fila[0] = product.Almacen;
                fila[1] = product.Nombre;
                fila[2] = product.Referencia;
                fila[3] = product.Color;
                fila[4] = product.Dimensiones;
                fila[5] = product.Precio + "";
                
                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Gamestore.class.getName()).log(Level.SEVERE, null, ex);
        }

        conexion.cerrar();        
    }//GEN-LAST:event_OnPressConsultar

    private void OnPressAddToShoppingCart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnPressAddToShoppingCart
        // TODO add your handling code here:
        int productIdx = ConsolasT.getSelectedRow();
        
        if(productIdx == -1){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un producto","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        Product product = products.get(productIdx);
        CarritoDeCompras.AddProduct(product);
        Carrito.DrawTable();
        
        JOptionPane.showMessageDialog(this, "Producto añadido");
    }//GEN-LAST:event_OnPressAddToShoppingCart
  
  ConexionBD conexion = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadeB;
    private javax.swing.JTable ConsolasT;
    private javax.swing.JButton ConsultarB;
    private javax.swing.JLabel FondoL;
    private javax.swing.JLabel JavaVersionL;
    private javax.swing.JLabel NombresL;
    private javax.swing.JScrollPane TablaSP;
    private javax.swing.JLabel TituloL;
    private javax.swing.JLabel VersionL;
    // End of variables declaration//GEN-END:variables
}
