/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_Control;

import Servicios.CarritoDeCompras;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Servicios.ConexionBD;
import Servicios.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class ConsultasVideo extends javax.swing.JFrame {

    static ArrayList<Product> products = new ArrayList<>();

    /**
     * Creates new form Consultas
     */
    public ConsultasVideo() {
        this.setLocationRelativeTo(null);
        conexion = new ConexionBD();
        conexion.usarBD("proyecto_final");
        conexion.conectar();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablaSP = new javax.swing.JScrollPane();
        JuegosT = new javax.swing.JTable();
        TituloL = new javax.swing.JLabel();
        ConsultarB = new javax.swing.JButton();
        AñadeB = new javax.swing.JButton();
        JavaVersionL = new javax.swing.JLabel();
        VersionL = new javax.swing.JLabel();
        NombresL = new javax.swing.JLabel();
        FondoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Videojuegos");
        setMinimumSize(new java.awt.Dimension(471, 540));
        setPreferredSize(new java.awt.Dimension(471, 540));
        setResizable(false);
        setSize(new java.awt.Dimension(471, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JuegosT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaSP.setViewportView(JuegosT);

        getContentPane().add(TablaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 390, 300));

        TituloL.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        TituloL.setForeground(new java.awt.Color(255, 255, 255));
        TituloL.setText("Consulta Videojuegos");
        getContentPane().add(TituloL, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        ConsultarB.setBackground(new java.awt.Color(204, 204, 255));
        ConsultarB.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        ConsultarB.setForeground(new java.awt.Color(0, 0, 102));
        ConsultarB.setText("CONSULTAR");
        ConsultarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarBActionPerformed(evt);
            }
        });
        getContentPane().add(ConsultarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 180, 50));

        AñadeB.setBackground(new java.awt.Color(204, 204, 255));
        AñadeB.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        AñadeB.setForeground(new java.awt.Color(0, 0, 102));
        AñadeB.setText("Añadir al carrito");
        AñadeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadeBActionPerformed(evt);
                AñadeBOnPressAddToShoppingCart(evt);
            }
        });
        getContentPane().add(AñadeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 180, 50));

        JavaVersionL.setForeground(new java.awt.Color(255, 255, 255));
        JavaVersionL.setText("Java: 1.8.0_111; Java HotSpot(TM) 64-Bit Server VM 25.111-b14");
        JavaVersionL.setToolTipText("");
        getContentPane().add(JavaVersionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        VersionL.setForeground(new java.awt.Color(255, 255, 255));
        VersionL.setText("Product Version: Apache NetBeans IDE 12.2");
        VersionL.setToolTipText("");
        getContentPane().add(VersionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        NombresL.setForeground(new java.awt.Color(255, 255, 255));
        NombresL.setText("Andrés Charria / Catalina Alba / Sergio Pulido / Laura Londoño  ");
        getContentPane().add(NombresL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, -1));

        FondoL.setIcon(new javax.swing.ImageIcon("C:\\Users\\meaf7\\Downloads\\WhatsApp Image 2021-06-09 at 7.37.43 PM.jpeg")); // NOI18N
        getContentPane().add(FondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -680, 900, 1620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarBActionPerformed
        
        ConsultarB.setVisible(false);
        
        ResultSet resultado = null;

        DefaultTableModel tabla = new DefaultTableModel();
        JuegosT.setModel(tabla);

        tabla.addColumn("Almacen");
        tabla.addColumn("Nombre");
        tabla.addColumn("Referencia");
        tabla.addColumn("Tipo");
        tabla.addColumn("Precio");

        resultado = conexion.consultarBD("select * from videojuegos;");

        String fila[] = new String[5];
        try {
            while (resultado.next()) {

                Product product = new Product(resultado,true);
                products.add(product);

                fila[0] = product.Almacen;
                fila[1] = product.Nombre;
                fila[2] = product.Referencia;
                fila[3] = product.Tipo;
                fila[4] = product.Precio + "";

                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Gamestore.class.getName()).log(Level.SEVERE, null, ex);
        }

        conexion.cerrar();        
    }//GEN-LAST:event_ConsultarBActionPerformed

    private void AñadeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadeBActionPerformed

    }//GEN-LAST:event_AñadeBActionPerformed

    private void AñadeBOnPressAddToShoppingCart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadeBOnPressAddToShoppingCart
        // TODO add your handling code here:
        int productIdx = JuegosT.getSelectedRow();

        if (productIdx == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un producto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Product product = products.get(productIdx);
        CarritoDeCompras.AddProduct(product);
        Carrito.DrawTable();

        JOptionPane.showMessageDialog(this, "Producto añadido");
    }//GEN-LAST:event_AñadeBOnPressAddToShoppingCart

    ConexionBD conexion = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadeB;
    private javax.swing.JButton ConsultarB;
    private javax.swing.JLabel FondoL;
    private javax.swing.JLabel JavaVersionL;
    private javax.swing.JTable JuegosT;
    private javax.swing.JLabel NombresL;
    private javax.swing.JScrollPane TablaSP;
    private javax.swing.JLabel TituloL;
    private javax.swing.JLabel VersionL;
    // End of variables declaration//GEN-END:variables
}
