/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_Control;

import Servicios.CarritoDeCompras;
import Servicios.Product;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Laura Londoño
 */
public class Factura extends javax.swing.JFrame {

    static float finalValue = 0;
    
    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
        DrawTable();
    }
    
    public static void DrawTable(){
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);  // Limpio la tabla
        String fila[] = new String[2];
        
        finalValue = 0;
        
        for (int i = 0; i < CarritoDeCompras.products.size(); i++) {
            
            Product product = CarritoDeCompras.products.get(i);
            
            fila[0] = product.Nombre;
            fila[1] = product.Precio + "";
            
            finalValue += product.Precio;
            
            model.addRow(fila);
        }
        
        priceLabel.setText("Precio total: "+finalValue);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(399, 461));
        setPreferredSize(new java.awt.Dimension(399, 461));
        setResizable(false);
        setSize(new java.awt.Dimension(399, 461));
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 11, 379, 270);

        jButton1.setText("Pagar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPressBuy(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 380, 100, 50);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPressDelete(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 380, 100, 50);

        jButton3.setText("Cancelar");
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 380, 100, 50);

        priceLabel.setBackground(new java.awt.Color(153, 255, 255));
        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("Price: ");
        getContentPane().add(priceLabel);
        priceLabel.setBounds(130, 284, 140, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\meaf7\\Downloads\\WhatsApp Image 2021-06-09 at 7.37.43 PM.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 399, 463);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void onPressBuy(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPressBuy
        // TODO add your handling code here:
        if(finalValue <= 0){
            JOptionPane.showMessageDialog(this, "No hay productos en el carrito","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        JOptionPane.showMessageDialog(this, "Compra exitosa","Compra",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_onPressBuy

    private void onPressDelete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPressDelete
        // TODO add your handling code here:      

        int productIdx = jTable1.getSelectedRow();
        
        if(productIdx == -1){
            JOptionPane.showMessageDialog(this, "You must select one product","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int op = JOptionPane.showConfirmDialog(this, "Seguro quieres borrar este producto?");
        
        if(op == JOptionPane.CANCEL_OPTION)
            return;
        
        Product product = CarritoDeCompras.products.get(productIdx);
        finalValue -= product.Precio;
        
        priceLabel.setText("Precio total: "+finalValue);
        
        CarritoDeCompras.products.remove(productIdx);
        ((DefaultTableModel)jTable1.getModel()).removeRow(productIdx);

    }//GEN-LAST:event_onPressDelete

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private static javax.swing.JLabel priceLabel;
    // End of variables declaration//GEN-END:variables
}
