/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista_Control;
import javax.swing.JOptionPane;
import Servicios.ConexionBD;

public class Gamestore extends javax.swing.JFrame {

    /**
     * Creates new form Carrito
     */
    public Gamestore() {
        this.setLocationRelativeTo(null);
        conexion = new ConexionBD();
        conexion.usarBD("proyecto_final");
        conexion.conectar();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloL = new javax.swing.JLabel();
        ConsolasB = new javax.swing.JButton();
        JuegosB = new javax.swing.JButton();
        CarroB = new javax.swing.JButton();
        SalirB = new javax.swing.JButton();
        NombresL = new javax.swing.JLabel();
        VersionL = new javax.swing.JLabel();
        JavaVersionL = new javax.swing.JLabel();
        FondoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloL.setFont(new java.awt.Font("Tw Cen MT", 1, 67)); // NOI18N
        TituloL.setForeground(new java.awt.Color(255, 255, 255));
        TituloL.setText("Game Store");
        getContentPane().add(TituloL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 340, 110));

        ConsolasB.setBackground(new java.awt.Color(204, 204, 255));
        ConsolasB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        ConsolasB.setForeground(new java.awt.Color(0, 0, 102));
        ConsolasB.setText("INICIAR BUSQUEDA CONSOLAS");
        ConsolasB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ConsolasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsolasBActionPerformed(evt);
            }
        });
        getContentPane().add(ConsolasB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 300, 50));

        JuegosB.setBackground(new java.awt.Color(204, 204, 255));
        JuegosB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        JuegosB.setForeground(new java.awt.Color(0, 0, 102));
        JuegosB.setText("INICIAR BUSQUEDA VIDEOJUEGOS");
        JuegosB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JuegosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuegosBActionPerformed(evt);
            }
        });
        getContentPane().add(JuegosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 300, 50));

        CarroB.setBackground(new java.awt.Color(204, 204, 255));
        CarroB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        CarroB.setForeground(new java.awt.Color(0, 0, 102));
        CarroB.setText("CARRITO");
        CarroB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CarroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPressFactura(evt);
            }
        });
        getContentPane().add(CarroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 170, 50));

        SalirB.setBackground(new java.awt.Color(255, 153, 153));
        SalirB.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        SalirB.setForeground(new java.awt.Color(0, 0, 102));
        SalirB.setText("SALIR");
        SalirB.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SalirB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBActionPerformed(evt);
            }
        });
        getContentPane().add(SalirB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 80, 40));

        NombresL.setForeground(new java.awt.Color(255, 255, 255));
        NombresL.setText("Andrés Charria / Catalina Alba / Sergio Pulido / Laura Londoño  ");
        getContentPane().add(NombresL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        VersionL.setForeground(new java.awt.Color(255, 255, 255));
        VersionL.setText("Product Version: Apache NetBeans IDE 12.2");
        VersionL.setToolTipText("");
        getContentPane().add(VersionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        JavaVersionL.setForeground(new java.awt.Color(255, 255, 255));
        JavaVersionL.setText("Java: 1.8.0_111; Java HotSpot(TM) 64-Bit Server VM 25.111-b14");
        JavaVersionL.setToolTipText("");
        getContentPane().add(JavaVersionL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        FondoL.setIcon(new javax.swing.ImageIcon("C:\\Users\\meaf7\\Downloads\\WhatsApp Image 2021-06-09 at 7.37.43 PM.jpeg")); // NOI18N
        getContentPane().add(FondoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SalirBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBActionPerformed
       JOptionPane.showMessageDialog(null, "Se ha terminado con la ejecución" , "Conexion Terminada", JOptionPane.INFORMATION_MESSAGE);
       System.exit(0);
    }//GEN-LAST:event_SalirBActionPerformed

    private void JuegosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuegosBActionPerformed
        ConsultasVideo consul = new ConsultasVideo(); 
        consul.setVisible(true);
    }//GEN-LAST:event_JuegosBActionPerformed

    private void ConsolasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsolasBActionPerformed
        ConsultasConso consul1 = new ConsultasConso(); 
        consul1.setVisible(true);
    }//GEN-LAST:event_ConsolasBActionPerformed

    private void onPressFactura(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPressFactura
        Carrito fact = new Carrito(); 
        fact.setVisible(true);
    }//GEN-LAST:event_onPressFactura

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gamestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gamestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gamestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gamestore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gamestore().setVisible(true);
            }
        });
    }
      ConexionBD conexion = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CarroB;
    private javax.swing.JButton ConsolasB;
    private javax.swing.JLabel FondoL;
    private javax.swing.JLabel JavaVersionL;
    private javax.swing.JButton JuegosB;
    private javax.swing.JLabel NombresL;
    private javax.swing.JButton SalirB;
    private javax.swing.JLabel TituloL;
    private javax.swing.JLabel VersionL;
    // End of variables declaration//GEN-END:variables
}
